export default {
    GET_PRODUCT: 'GET_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_CATEGORY: 'UPDATE_PRODUCT_CATEGORY',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PROJECT_PRODUCTS: 'GET_PROJECT_PRODUCTS',
    CREATE_PRODUCT: 'CREATE_PRODUCT',

    GET_PROJECT_CATEGORIES: 'GET_PROJECT_CATEGORIES',
    GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
    GET_PROJECT_PRODUCT_TYPES: 'GET_PROJECT_PRODUCT_TYPES',

    CREATE_PRODUCT_TYPE: 'CREATE_PRODUCT_TYPE',

    GET_CATEGORY: 'GET_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    GET_CATEGORIES: 'GET_CATEGORIES',
    CREATE_CATEGORY: 'CREATE_CATEGORY'
}