export default {
    GET_PRODUCTS: 'GET_PRODUCTS',
    CREATE_PRODUCT: 'CREATE_PRODUCT',

    GET_CATEGORY: 'GET_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    GET_CATEGORIES: 'GET_CATEGORIES',
    CREATE_CATEGORY: 'CREATE_CATEGORY'
}