export default {
    GET_PRODUCT: 'GET_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_CATEGORY: 'UPDATE_PRODUCT_CATEGORY',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PROJECT_PRODUCTS: 'GET_PROJECT_PRODUCTS',
    CREATE_PRODUCT: 'CREATE_PRODUCT',

    GET_PROJECT_CATEGORIES: 'GET_PROJECT_CATEGORIES',
    GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
    GET_PROJECT_PRODUCT_TYPES: 'GET_PROJECT_PRODUCT_TYPES',

    GET_PRODUCT_TYPE: 'GET_PRODUCT_TYPE',
    GET_PRODUCT_TYPE_ATTRS: 'GET_PRODUCT_TYPE_ATTRS',
    CREATE_PRODUCT_TYPE: 'CREATE_PRODUCT_TYPE',
    UPDATE_PRODUCT_TYPE: 'UPDATE_PRODUCT_TYPE',

    GET_PRODUCT_VARIANTS: 'GET_PRODUCT_VARIANTS',
    CREATE_VARIANT: 'CREATE_VARIANT',
    UPDATE_VARIANT: 'UPDATE_VARIANT',
    REMOVE_VARIANT: 'REMOVE_VARIANT',

    ADD_ATTRIBUTE: 'ADD_ATTRIBUTE',
    REMOVE_ATTRIBUTE: 'REMOVE_ATTRIBUTE',
    UPDATE_VARIANT_ATTRIBUTE: 'UPDATE_VARIANT_ATTRIBUTE',

    GET_CATEGORY: 'GET_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    GET_CATEGORIES: 'GET_CATEGORIES',
    CREATE_CATEGORY: 'CREATE_CATEGORY',

    GET_TEAMS: 'GET_TEAMS',
    UPDATE_TEAM: 'UPDATE_TEAM',
    UPDATE_PERMISSION: 'UPDATE_PERMISSION',
    REMOVE_MEMBER: 'REMOVE_MEMBER',

    PRODUCT_ATTR_TYPES: [
        'text', 'boolean', 'localizedText', 'enum', 'localizedEnum',
        'number', 'money', 'date', 'time', 'dateTime', 'set', 'reference'],

    PERMISSIONS: ['none', 'view', 'manage']
}